version: '3.4'

services:
  backend:
    build:
      context: .
      dockerfile: Test.Backend/Dockerfile
    ports:
     - "6060:80"
  database:
    image: "postgres" # use latest official postgres version
    ports:
      - "5432:5432"