version: '3.4'

services:
  backend:
    image: test.backend:0.1
    build:
      context: .
      dockerfile: Test.Backend/Dockerfile.staging
    ports:
      - "6060:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging

  database:
    image: "postgres"
    ports:
      - "6061:5432"
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_USER=postgres
      - POSTGRES_DB_NAME=test