version: '3.4'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  database:
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_USER=postgres
      - POSTGRES_DB_NAME=test
